### ISSUE TITLE
"remove" (for JS arrays) updated version

### ISSUE THREAD

**Issue by celwell** [30-seconds/30-seconds-of-code#1071]
Hey,

Here is an improved (I think) version of this snippet (https://www.30secondsofcode.org/js/s/remove):

```js
const remove = (arr, f) => {
    return arr.reduce((acc, v) => {
        if (f(v)) {
            acc.push(v);    
        }
        return acc;
    }, []);
};
```

**Please let me know if I should move forward with a PR.**

NOTE: The `index` and `array` args to the function seemed superfluous and just incidental to the original implementation, but I might be able to keep them if necessary. Also, I would suggest making this function do the opposite: remove the elements that the predicate returns `true` for. E.g., Clojure's `remove` function behaves that way (https://clojuredocs.org/clojure.core/remove).

Thanks,
Chris

**Comment by Chalarangelo** [comment]
Hello, thanks for the suggestion. 

However, `remove` mutates the original array, which is the intended behavior. This might not be communicated properly at this time, which is why I would suggest to update the description to something more like:
 ```
Removes elements from an array for which the given function returns `false`.
```  

This would definitely benefit the snippet and not alter its behavior which is intentional.
