### ISSUE TITLE
Add 30-seconds-of-C++

### ISSUE THREAD

**Issue by anuragnatoo** [30-seconds/30-seconds-of-code#1132]
## Description 

Hey all!
It would be great to have a **30-seconds-of-C++** repository.
C++ is also used in competitive programming where snippets of small functions for example gcd of two numbers,checking primality of a number etc. are required.
We can also add  some **templates** which can be used in competitive programming in C++.

**Comment by Chalarangelo** [comment]
Hey, there. Thanks for the suggestion!

We currently lack the manpower and expertise to do so, apart from the fact that most of our community seems to be mainly involved in webdev and interested in languages such as JS, CSS, React and Python for the most part, which is why we have put new language projects on hold for a little while.

**Comment by anuragnatoo** [comment]
Okay! I will always be ready to contribute to the C++ project if its developed in the future
