### ISSUE TITLE
Snippet data in JSON

### ISSUE THREAD

**Issue by sQVe** [30-seconds/30-seconds-of-code#1145]
Hey :wave:,

I'm the maintainer of both https://github.com/sQVe/30s and https://github.com/sQVe/30-seconds-of-code-ultisnips, which are not unable to update due to the lack of `snippet_data/snippets.json`. 

Do you have any recommendations on how custom clients could consume the snippets provided here? It would be a shame if the previously provided JSON format was removed.

:pray:

**Comment by Chalarangelo** [comment]
Unfortunately we have moved most of the logic and systems to our integration pipeline as the main objective is to be able to publish and distribute code snippets via the website and this sped up development on that immensely. I'm afraid that if you want to extract JSON data you would have to write your own extraction logic and make sure that everything is up to date whenever we change formats in the future. I know this is probably a bummer, but it made a lot of things possible, which is why we ultimately set up a centralized pipeline instead of many smaller ones to deal with the issue.

**Comment by sQVe** [comment]
@Chalarangelo Alright. I can see the reasoning behind this but it excludes a alternative ecosystem. It also deprecates the current `npm` package.

**Comment by Chalarangelo** [comment]
The npm package is discontinued due to the fact that it was technically never updated and that we cannot maintain consistent enough performance and quality so that we are both a learning resource and a package, so it didn't make the cut. It was, like many other things, an experiment that failed to keep up due to lack of interest and manpower. 

We are more focused on the website, as a narrower scope and not trying to do too many things at once will produce higher quality results. I agree that some features were nice, but unfortunately we only have so many resources and we want to keep the core experience - that is providing high quality explanatory content - intact and ensure it's always our top priority.

**Comment by manukdup** [comment]
Good delete my duplicates accounts.
