### ISSUE TITLE
Hacktoberfest and PR closing with invalid label

### ISSUE THREAD

**Issue by jikuja** [30-seconds/30-seconds-of-code#1324]
Looks like some PRs are closed with invalid label and `However, I don't think this PR provides a lot of value for most of our readers.` or similar explanation.

I want to raise a discussion if marking PRs done in good faith is worth of tagging with **invalid** label just because content has no value for most of the readers.  It hurts people participating hacktoberfest.

If providing content which has too simple or too complicated is worth of **invalid** label, please add comment about that in contribution guidelines and README.

**Comment by Chalarangelo** [comment]
Hello, we are getting a lot of low-effort, low-value and high-attitude PRs (yours included). We mark PRs that are spammy/annoying/persistently problematic or irrelevant for future contributors as `invalid` or as we see fit to ensure ease of finding valid contributions. We try to process valid PRs as fast as we can, so we don't really have the time to explain the issues we find in every single PR that shows little to no effort or has no chance of being merged due to it not aligning with our vision of what content we think is relevant to our readers.

The rules of hacktoberfest clearly state that if your PRs are not merged or accepted, they don't count, so it makes no difference to you as a participant what we tag `invalid` and whatnot. 

Thank you.
