### ISSUE TITLE
Clarification of rules of participation

### ISSUE THREAD

**Issue by sesam** [30-seconds/30-seconds-of-code#1353]
1. Is it 100% required to install your software globally?
I'm not sure it's OK to demand contributors to globally install software in order to contribute. (Would you like a side-dish of a crypto miner with that install?)

2. Are no PR:s for adding new snippets accepted without a corresponding issue?
I noticed quite some open PR:s without corresponding issues, so I guessed it would be OK to not open an issue, as it might be faster to handle as a PR, when code speaks more than English approximations of the intended feature.

**Comment by Chalarangelo** [comment]
1. No, but if you make a mistake in following the rules that's on you. The package we require you to install makes contributing easier and makes sure we don't have to check for some of the rules in PRs. Due to limited time during Hacktoberfest, PRs with multiple contribution rule violations will be closed without further investigation.

2. PRs are accepted without issues, if they meet the criteria and the added snippets are worthwhile. If you are uncertain if a snippet is valuable, you can always open an issue and discuss it. We do our best to help contributors who bring up valid ideas submit PRs that we will actually accept (i.e. if it's a valid idea, we'll assign the issue to you and if you open a PR within a reasonable timeframe (a week or two I suppose sounds reasonable), we'll merge it after reviewing it and helping out with its implementation). If someone else opens a PR for an issue/idea you are working on, we'll hold off on merging their PR unless you abandon the project or are MIA for a while (same timeframe applies here).

Hope that helps.

**Comment by sesam** [comment]
Thank you for clarifying. I started considering if a github action could take care of the pr rules check. It could perhaps also cause some misuse of the pr pipeline instead of checking syntax locally though. And finding a code style checker for the specific chosen semi-standard might be tricky. So I'll bail on this for now, but thank you anyway.
