### ISSUE TITLE
[FEATURE] How about a 30 seconds of git ?

### ISSUE THREAD

**Issue by devAxeon** [30-seconds/30-seconds-of-code#737]
Everything is in the title ;)

**Comment by Chalarangelo** [comment]
Hey there! I hope I'm speaking for everyone on the team when I say that we are constantly considering new ideas, but we have very limited time. 

**git** has not been discussed in depth but, like SQL or some other projects, might be a bit esoteric or need to be clarified with examples for people to really understand advanced use-cases. We are open to discussing potential 30 seconds projects and/or supporting new ones, even if we are not the ones who start them (e.g. 30 seconds of Python code). If you have a more clear plan or idea of how you would like to see such a project implemented, so that it is not just a more understandable manual of git, please comment below and let us know. 😉

**Comment by Chalarangelo** [comment]
Closing due to little interest in this idea. Might reopen if someone has anything useful to suggest for this.
