### ISSUE TITLE
isString return false for object strings

### ISSUE THREAD

**Issue by gillesdami** [30-seconds/30-seconds-of-code#754]
## Bug description 

"Checks if the given argument is a string."
isString(new String("hi"));
> false

## Why it should be fixed

Using the String constructor is a bad practice, but it's still legit javascript so this case should be properly handled. If you don't want to handle this case, you should probably make it more clear by naming the function isStringPrimitive or making it clear in the first sentence of the description else it may confuse beginners.

## The fix

Curently:

```js
const isString = val => typeof val === 'string';
```

fixed: (This fix is inspired by underscore)

```js
const isString = val => Object.prototype.toString.call(val) === "[object String]";
```

**Comment by Chalarangelo** [comment]
I'm not against this honestly, but there might have been a reason why we implemented this in the first place. I'm labelling `discussion` to see if anyone else remembers why we did this that way.

**Comment by skatcat31** [comment]
`String` instances are not strings, they are objects. While they can be coerced, they are a wrapper around a string, and are mutable. strings are not mutable in javascript and that's the biggest difference.

This however makes very little difference to anything.

I would however be against this change as it won't actually test if it's a string primitive or a string instance. We might want another function that checks differently since there are different use cases for each in edges where you would even use this snippet.

As a quick test: `typeof JSON.parse('"test"')` is a string primitive. The ONLY way to get an Object and not a string primitive is to use a constructor, and that is a conscious developer decision, meaning it would be a case that can not be encountered by most situations where you would use this snippet. If a library returns a String instance this would also be known in advance due to documentation.

So I think this staying as a snippet that checks for string literals and not `String`s is probably for the best since the only place you'd want to check for a string is provided input(network or user provided)

**Comment by Chalarangelo** [comment]
I agree with @skatcat31's reasoning. Let's just document the functionality properly and move on.

**Comment by gillesdami** [comment]
@Chalarangelo @skatcat31 Ok fine, should I make a pull request on some files or are you handling it yourself?

**Comment by Chalarangelo** [comment]
We can handle it, I'll do it later today.
