### ISSUE TITLE
I think it will change the allEqual definition in docs

### ISSUE THREAD

**Issue by OhIAmFine** [30-seconds/30-seconds-of-code#964]
As I can see in the README, the allEqual definition is like that:

```
  const allEqual = arr => arr.every(val => val === arr[0]);
```
But when I test  `allEqual([NaN, NaN])`, it will return false,

I think it need change the definition like that:
```
 const allEqual = arr => arr.every(val => Object.is(val, arr[0]));
```
when I test `allEqual([NaN, NaN])`, it will return true as I expect.

I just a poor learner at js, so please point out my mistake if I was wrong.

**Comment by Chalarangelo** [comment]
That's quite an interesting edge-case, actually, due to the fact that `NaN` is not equal to itself. `Object.is()` seems like a solution, but we should check if it has any other side-effects before changing the `allEqual` method. 

In any case, this is a very interesting observation and we should in any case do something about it - either update the code or add a comment about the edge-case.

**Comment by OhIAmFine** [comment]
Ok, that's your attention

**Comment by skatcat31** [comment]
If we do update the code it would be considered a breaking change because NaN is meant to be not equal to itself. So if we do go to the more "stable" Object.is() then we will need to note it

**Comment by Chalarangelo** [comment]
@skatcat31 We should add a comment either way. I do agree that `NaN`'s behavior is essentially by-design in this snippet. Maybe we just add a note about it and go our merry way?

**Comment by skatcat31** [comment]
Adding a comment either way is a good step, and I think keeping it the way it is now and noting it would be better.
